### ISSUE TITLE
Expired Pokemon still getting stuck

### ISSUE THREAD

**Issue by TheNewDarkOne** [istornz/iPokeGo#285] opened 2016-08-25 18:52 UTC
Despite the commit few days ago I'm still getting this issue a LOT. Expired pokemon keep flickering on the map and spamming notifications. As an example, a Vulpix expired and disappeared but every 1 second it'd reappear send a notification get removed then reappear send notification get removed etc. For some reason it keeps getting re-added to map even though it's expired and only way to fix it is to restart the app when this happens. It happens at least once or twice an hour.

**Comment by SnakeIz** [comment] 2016-08-28 20:41
Same issue, driving me crazy. Wish I knew or had someone that could compile the most recent code for me

**Comment by TheNewDarkOne** [comment] 2016-08-29 04:36
Snake, it's not fixed in latest code, that's what my ticket is about. I have absolute latest code compiled fresh and it still happens.

**Comment by istornz** [comment] 2016-08-30 09:53
@TheNewDarkOne @SnakeIz What is the type of your server ?

**Comment by TheNewDarkOne** [comment] 2016-08-30 15:54
https://github.com/PokemonGoMap/PokemonGo-Map

Latest dev.

**Comment by Bizadon** [comment] 2016-09-06 07:11
@istornz have the same issue. I admited that issue occures when you switch on showing only lured pokestop, whats wrong with it?

**Comment by istornz** [comment] 2016-09-11 10:52
@Bizadon @TheNewDarkOne I think the problem is fixed with the latest commit, can you confirm plz ?

**Comment by Bizadon** [comment] 2016-09-14 19:04
@istornz Updated today, still have pokemons, that get stuck. Its looks like: it dissapears, then appears 2-3 times again for just a moment (you can look on it only if you watch over the pokemon) without timer ovet it, just having "-" instead of timer. Not so much problem if notifications for that pokemon are off, but if notifications are on it just like you tap the notification, map follows the location of appearing pokemon, but it is already dissapeared and nothing there on map.

**Comment by leolobato** [comment] 2016-09-18 17:14
Found the issue. This will constantly happen when the server clock is different than the iOS device.

**Comment by Bizadon** [comment] 2016-09-18 21:15
@leolobato when the clock is different then the timer is more or less, just that. I tried it with server clock -1hour, pokemons just have much more time to expire. In this situation they are getting stuck and have "-" instead of timer.

**Comment by leolobato** [comment] 2016-09-18 21:21
In my case the server was off by -6 hours (I think). The pokemons would be added to the map by ```- processPokemonFromJSON:usingContext:``` and then removed by ```-cleanData```.

**Comment by istornz** [comment] 2016-10-01 21:41
@leolobato @Bizadon Ok nice !
I close the issue now, reopen if needed.

**Closed by istornz** 2016-10-01 21:41 UTC
