### ISSUE TITLE
Pogom timer bug

### ISSUE THREAD

**Issue by Bizadon** [istornz/iPokeGo#274] opened 2016-08-23 08:39 UTC
Sometimes when I use pogom server a bug appears in app. But in browser version everything allright with time. Seems like there is two timers over a pokemon laid one over another.

![image](https://cloud.githubusercontent.com/assets/20676961/17885440/ffce0498-6925-11e6-9c1a-e3f90202ceff.png)

**Comment by Bizadon** [comment] 2016-08-27 14:40
@istornz What is with it?

**Comment by istornz** [comment] 2016-08-28 13:03
@Bizadon If you open settings and directly close the tab do you have the same bug ?

**Comment by Bizadon** [comment] 2016-08-29 19:06
@istornz yes, the same, but I dont know is it important now, because it seems that pogom doesnt work on their map...

**Comment by istornz** [comment] 2016-09-11 10:53
@Bizadon @TheNewDarkOne I think the problem is fixed with the latest commit, can you confirm plz ?

**Comment by istornz** [comment] 2016-10-01 21:39
I close this issue please reopen if needed.

**Closed by istornz** 2016-10-01 21:39 UTC
