### ISSUE TITLE
Feature Requst: add a login for opening up the server Ip on the internet browser or ipokego

### ISSUE THREAD

**Issue by wardude202** [istornz/iPokeGo#91] opened 2016-07-29 23:11 UTC
As the title says, if this is possible could someone guide me through how to do it

**Comment by markvl91** [comment] 2016-07-31 19:08
Duplicate of #72?

**Comment by INGY23** [comment] 2016-08-01 20:27
Guessing not, I believe what wardude is after is a way of securing the webpage so that it asks for a username and password when opening so other people can't use it.

**Comment by wardude202** [comment] 2016-08-02 11:13
That's exactly what I'd love @INGY

**Comment by istornz** [comment] 2016-08-02 17:09
@wardude202 @INGY23 Can you give me in mp any server with this protection ?

**Comment by istornz** [comment] 2016-08-12 10:23
Now added in the latest build. I close

**Closed by istornz** 2016-08-12 10:23 UTC
Labels: enhancement
